version: "0.1.0"

services:
  run-tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=${TZ:-$(cat /etc/timezone)}
    volumes:
      - ./requirements.txt:/usr/src/app/requirements.txt
      - data:/usr/src/app/data
    working_dir: /usr/src/app
    ports:
      - "127.0.0.1:8080:5000"
    command: [ "cron", "-f" ]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - run-tests

volumes:
  data: